### ISSUE TITLE
Failed to build from source

### ISSUE THREAD

**Issue by SG-phimeca** [impact/impact#109] opened 2016-03-04 10:46 UTC
Building impact from source fails at the step

    go install github.com/impact/impact/impact/

which raises

src/github.com/impact/impact/crawl/github.go:9:2: cannot find package "code.google.com/p/goauth2/oauth" in any of:
	~/golang/go/src/code.google.com/p/goauth2/oauth (from $GOROOT)
	~/golang/packages/src/code.google.com/p/goauth2/oauth (from $GOPATH)

(I replaced the path to my home by “~”).

**Comment by dietmarw** [comment] 2016-03-04 11:53
Confirmed: `goauth2` is deprecated in favour of [oauth2](https://godoc.org/golang.org/x/oauth2)

Simply updating the imports does not help though since the API has changed slightly.
@mtiller: Any chance to take a quick look at this. As far as I could see the `crawl/github.go` needs updating so that compiling works again.

**Comment by xogeny** [comment] 2016-03-04 12:30
Sylvain, good to see you here. :smiley:

I will try to take a look at this weekend, but I'm just starting a large project so things are very tight right now.  Hopefully it will be something simple.

**Comment by SG-phimeca** [comment] 2016-03-04 13:43
Nothing urgent: their are the compiled binaries.

**Comment by dietmarw** [comment] 2016-04-19 19:05
@mtiller did some fixes in 5b39c1925ac819449773d9161bda1fc691d5229c 
I'll check if that resolves the issue.

**Comment by dietmarw** [comment] 2016-04-19 19:18
Confirmed as fixed. Released as v0.8.1

**Closed by dietmarw** 2016-04-19 19:18 UTC
Labels: bug
